version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.1
    command: start-dev
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin_password
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
    networks:
      - app-network

networks:
  app-network:
    external: true